%% Create masks
% The next lines of code will create masks at the resolution of the DTI scan that 
% can be used for tractography. The tractography masks will be created 
% from the muscle segmentation of the anatomical scan, which will be
% downsampled to match the DTI resolution.

% (It is assumed that example_preprocessing.m has been done so that all
% required files for mask creation are available.)

datapath       = fullfile(pwd,'data','001');    % raw data path for subject 1
results_path   = fullfile(pwd,'results','001'); % results path for subject 1
DTI_filename   = fullfile(datapath,'CALF001_DTI.nii.gz');  % name of DTI data for subject 1
FIB_filename   = fullfile(results_path,'CALF001_DTI_LPCA.fib.gz'); % name of .fib file for subject 1
label_filename = fullfile(datapath,'masks','CALF001_T1_anat_labels.nii.gz'); % name of the segmentation file (generated by ITK-snap, for example)
DTI_masks_path = fullfile(results_path,'DTI_masks'); % path name where the tractography masks will be saved to

% Make masks/surfaces for all labels present in the label file
% Type help MakeSurfaceAndMasks for more information on how to use this
% function.
mask_filenames = MakeSurfaceAndMasks( label_filename,DTI_filename,...
    'ResultsPath',DTI_masks_path);

% Make a mask to exclude regions with FA values below/above the provided
% threshold.
% Type help MakeFAmask for more information on how to use this function.
FA_threshold = [0.1 0.5];
filename.FA_mask = MakeFAmask(FIB_filename,FA_threshold,...
    'ResultsPath',DTI_masks_path);

% Alternative options:
% Make masks+surfaces for labels with the names in LabelNames
% LabelNames = {'MG'};
% mask_filenames = MakeSurfaceAndMasks( segm_filename,DTI_filename,...
%     'LabelNames',LabelNames,...
%     'ResultsPath',fullfile(results_path,'DTI_masks'));

% Make masks+surfaces for labels with the numbers in LabelNumbers
% LabelNumbers = 1;
% mask_filenames = MakeSurfaceAndMasks( segm_filename,DTI_filename,...
%     'LabelNumbers',LabelNumbers,...
%     'ResultsPath',fullfile(results_path,'DTI_masks'));

